# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Set default Provider to be VirtualBox
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  # Use Ubuntu 14.04 VirtualBox
  config.vm.box = "ubuntu/trusty64"

  # Customize virtual hardware
  config.vm.provider :virtualbox do |v|
    v.name = "Pseudo-Distributed-HDFS"
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end

  # Web interface for the NameNode
  config.vm.network "forwarded_port", guest: 50070, host: 50070
  # Web interface for the ResourceManager
  config.vm.network "forwarded_port", guest: 8088, host: 8088

  # Installations and Configurations
  config.vm.provision :shell, path: "./bootstrap.sh", privileged: false
end
