# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Set default Provider to be VirtualBox
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

  # Use Ubuntu 14.04 VirtualBox
  config.vm.box = "ubuntu/trusty64"

  # Customize virtual hardware
  config.vm.provider :virtualbox do |v|
    v.name = "Standalone-HDFS"
    v.customize ["modifyvm", :id, "--memory", "4096"]
  end
  # Installations and Configurations
  config.vm.provision :shell, path: "./bootstrap.sh", privileged: false

end
